name: Deploy Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      build-push-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: Set Commit Short
            id: vars
            run: echo "COMMITSHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Image'
            run: |
              docker buildx create --name home_controller_builder
              docker buildx use home_controller_builder
              docker buildx build --platform linux/arm64,linux/amd64,linux/arm/v7 -t ghcr.io/elijahnyp/home_controller:${COMMITSHA_SHORT} --push .
          - name: 'Update Deployment'
            run: |
              sed -i "s/ghcr.io\/elijahnyp\/home_controller:[a-f0-9]\+/ghcr.io\/elijahnyp\/home_controller:${COMMITSHA_SHORT}/g" deployment/deployment.yaml
          - name: 'Push New Manifests'
            run: |
              git add deployment/deployment.yaml
              git commit -m 'update deployment with new tag [skip ci]'
              git push